// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRqmbn25AC9uXlyvBL-gACN8A2qAzn0to',
    appId: '1:173267449415:web:568718ee2fde9957852362',
    messagingSenderId: '173267449415',
    projectId: 'product-app-e36d3',
    authDomain: 'product-app-e36d3.firebaseapp.com',
    storageBucket: 'product-app-e36d3.appspot.com',
    measurementId: 'G-F8L29252D9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIUfEbBMIA5jgRD0Z-_xD22nrLG66k0go',
    appId: '1:173267449415:android:7f40a8c4c5b7948d852362',
    messagingSenderId: '173267449415',
    projectId: 'product-app-e36d3',
    storageBucket: 'product-app-e36d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6iXZg5LU0cL78mxEh1HLPRoHZloGDtNs',
    appId: '1:173267449415:ios:92dcc3fc2f8e8142852362',
    messagingSenderId: '173267449415',
    projectId: 'product-app-e36d3',
    storageBucket: 'product-app-e36d3.appspot.com',
    iosBundleId: 'com.example.intern1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6iXZg5LU0cL78mxEh1HLPRoHZloGDtNs',
    appId: '1:173267449415:ios:92dcc3fc2f8e8142852362',
    messagingSenderId: '173267449415',
    projectId: 'product-app-e36d3',
    storageBucket: 'product-app-e36d3.appspot.com',
    iosBundleId: 'com.example.intern1',
  );
}
